export type ToyExchangeRequestStatus = 'PENDING' | 'ACCEPTED' | 'REJECTED';
export type ToyExchangeRequestMutation = { requestId:string;listingId:string;status:ToyExchangeRequestStatus;createdAt:string;respondedAt:string|null };
export type ToyExchangeRequestCard = ToyExchangeRequestMutation & { listingName:string;listingImageUrl:string|null;askingValueStars:number };
export type MyToyExchangeRequests = { sent:ToyExchangeRequestCard[];received:ToyExchangeRequestCard[] };
export function parseExchangeRequestMutationResponse(value:unknown):ToyExchangeRequestMutation{if(!isRecord(value)||!exact(value,['request'])||!isRecord(value.request))throw malformed();return parseMutation(value.request);}
export function parseMyExchangeRequestsResponse(value:unknown):MyToyExchangeRequests{if(!isRecord(value)||!exact(value,['sent','received'])||!Array.isArray(value.sent)||!Array.isArray(value.received))throw malformed();return{sent:value.sent.map(parseCard),received:value.received.map(parseCard)};}
function parseMutation(value:Record<string,unknown>):ToyExchangeRequestMutation{if(!exact(value,['requestId','listingId','status','createdAt','respondedAt']))throw malformed();const requestId=text(value.requestId),listingId=text(value.listingId),createdAt=time(value.createdAt),respondedAt=value.respondedAt===null?null:time(value.respondedAt);if(!requestId||!listingId||!status(value.status)||!createdAt||respondedAt===undefined||(value.status==='PENDING'&&respondedAt!==null)||(value.status!=='PENDING'&&respondedAt===null))throw malformed();return{requestId,listingId,status:value.status,createdAt,respondedAt};}
function parseCard(value:unknown):ToyExchangeRequestCard{if(!isRecord(value)||!exact(value,['requestId','listingId','listingName','askingValueStars','status','createdAt','respondedAt','listingImageUrl']))throw malformed();const base=parseMutation({requestId:value.requestId,listingId:value.listingId,status:value.status,createdAt:value.createdAt,respondedAt:value.respondedAt});const listingName=text(value.listingName);const listingImageUrl=value.listingImageUrl===null?null:https(value.listingImageUrl);if(!listingName||!Number.isSafeInteger(value.askingValueStars)||Number(value.askingValueStars)<0||listingImageUrl===undefined)throw malformed();return{...base,listingName,listingImageUrl,askingValueStars:Number(value.askingValueStars)};}
function malformed(){return new Error('Exchange request returned malformed data.');}function text(v:unknown){return typeof v==='string'&&v.trim()?v.trim():null;}function time(v:unknown):string|null|undefined{return typeof v==='string'&&v.trim()&&!Number.isNaN(Date.parse(v))?v:undefined;}function https(v:unknown):string|undefined{if(typeof v!=='string')return;try{return new URL(v).protocol==='https:'?v:undefined;}catch{return;}}function status(v:unknown):v is ToyExchangeRequestStatus{return v==='PENDING'||v==='ACCEPTED'||v==='REJECTED';}function exact(v:Record<string,unknown>,k:string[]){return Object.keys(v).length===k.length&&k.every((x)=>Object.prototype.hasOwnProperty.call(v,x));}function isRecord(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v);}
